services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/project-zero.cz/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/project-zero.cz/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - frontend
      - backend
  web:
    build:
      context: ./Project_Zero-web 
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - Project_Zero-web/app/.env                    
    restart: unless-stopped

  api:
    build:
      context: ./Project_Zero-api
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - Project_Zero-api/app/.env
    depends_on:
      - db                        
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    expose:
      - "5432"
    env_file:
      - Project_Zero-api/app/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data: {}