services:
  web:
    build:
      context: ./Project_Zero-web 
      dockerfile: Dockerfile
    env_file:
      - Project_Zero-web/app/.env                    
    ports:
      - '80:80'
    restart: unless-stopped

  api:
    build:
      context: ./Project_Zero-api
      dockerfile: Dockerfile
    env_file:
      - Project_Zero-api/app/.env
    ports:
      - '8000:8000'  
    depends_on:
      - db                        
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    env_file:
      - Project_Zero-api/app/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data: {}