"""Adding CASCADE ondelete

Revision ID: 98997071ed4f
Revises: 970c51073ed6
Create Date: 2025-04-07 22:42:38.313972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98997071ed4f'
down_revision: Union[str, None] = '970c51073ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('csrf_tokens_user_id_fkey', 'csrf_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'csrf_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('useractivity_logs_user_id_fkey', 'useractivity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'useractivity_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useractivity_logs', type_='foreignkey')
    op.create_foreign_key('useractivity_logs_user_id_fkey', 'useractivity_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'csrf_tokens', type_='foreignkey')
    op.create_foreign_key('csrf_tokens_user_id_fkey', 'csrf_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
